openapi: 3.0.1
info:
  title: HelloWorldSample
  description: API Definition of HelloWorldSample
  version: 1.0.0
servers:
- url: http://localhost:8290/helloWorld
paths:
  /:
    get:
      responses:
        default:
          description: Default response
